# Generated by Django 5.0.6 on 2026-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("cartao", "Cartão"),
                    ("parcela", "Parcela"),
                    ("caixa", "Caixa"),
                    ("boleto", "Boleto"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
